name: Create Diagram

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Undetach HEAD
      run:  git switch -

    - name: Repo Visualizer
      uses: githubocto/repo-visualizer@0.5.0
