name: .NET Nuget

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core 3.1.1
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 3.1.101

    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: latest

    - name: Set up nuget source
      run: nuget sources add -name "GitHub" -Source https://nuget.pkg.github.com/interlockledger/index.json -Username monoman@gmail.com -Password ${{ secrets.RegistryToken }}

    - name: Test with dotnet
      run: dotnet test --configuration Release -v:m | grep -v 'NAME_UNKNOWN:Package'

    - name: Pack nuget
      run: dotnet pack -o `pwd`/.nugets --configuration Release --no-build -v:m

    - name: Push nuget
      run: dotnet nuget push `pwd`/.nugets/*.nupkg -s GitHub
