name: .NET Nuget

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core 3.1.1
      uses: actions/setup-dotnet@v1.0.0
      with:
        dotnet-version: 3.1.101

    - uses: nuget/setup-nuget@v1
          with:
            nuget-api-key: ${{ secrets.RegistryToken }}
            nuget-api-key-source: GitHub
            nuget-version: latest

    - name: Test with dotnet
      run: dotnet test --configuration Release -v:m | grep -v 'NAME_UNKNOWN:Package'

    - name: Pack nuget
      run: dotnet pack -o `pwd`/.nugets --configuration Release --no-build -v:m

    - name: Push nuget
      run: dotnet nuget push `pwd`/.nugets/*.nupkg -s GitHub
