name: .NET Nuget

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core 2.2
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.207
    - name: Install additional dotnet 3.0
      run: sudo apt-get install dotnet-sdk-3.0
    - name: Build with dotnet
      run: dotnet build --configuration Release -v:m
    - name: Test with dotnet
      run: dotnet test --configuration Release --no-build -v:m
    - name: Pack nuget
      run: dotnet pack -o .nugets --configuration Release --no-build -v:m
    - name: Push nuget
      run:  sed -e "s/GH_TOKEN/${{ secrets.GITHUB_TOKEN }}/" NuGet.Config.template > NuGet.Config && dotnet nuget push .nugets/*.nupkg -s GitHub
